version: '3.4'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - kotlin-rest-docker-network
  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"
    networks:
      - kotlin-rest-docker-network
  kotlin-rest:
    image: kotlin-rest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/postgres
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
      SPRING.REDIS.HOST: redis
      SPRING.REDIS.PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - kotlin-rest-docker-network
networks:
  kotlin-rest-docker-network:
    driver: bridge
