version: '3'
services:
  postgres-dev:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  redis-dev:
    image: "redis"
    restart: always
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379:6379"