server:
  port: 8080
  servlet:
    context-path: /api

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
jwt:
  secret: 2Mkc1xx5meyCA7qpA2wUwhv9b

logging:
  level:
    com.github.raphasalomao.kotlinrestforum.application: DEBUG